<a href="https://colab.research.google.com/github/denverkim/WEBCRAWLING/blob/main/LAB2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
# 리스트
lst = [3,-5,7,4]
lst

[3, -5, 7, 4]

In [8]:
# 씨리즈
import pandas as pd

s = pd.Series([3,-5,7,4], index=['a', 'b', 'c', 'd'])
s
# s.mean()

a    3
b   -5
c    7
d    4
dtype: int64

In [14]:
# 딕셔너리로 데이터 프레임 만들기
dict = {'Country': ['Belgium', 'India', 'Brazil'],
        'Capital': ['Brussels', 'New Delhi', 'Brailia'],
        'Population':[11190846, 1303171035, 207847528]}
dict['Country'][0]
df = pd.DataFrame(dict)
df

   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil    Brailia   207847528

In [16]:
df.Population.mean()

np.float64(507403136.3333333)

In [22]:
# 리스트로 데이터 프레임 만들기
data = [['Jan',58,42,74,22,2.95],
        ['Feb',61,45,78,26,3.02],
  ['Mar',65,48,84,25,2.34],
  ['Apr',67,50,92,28,1.02]]
data
pd.DataFrame(data, columns = ['month','avg_high','avg_low','record_high','record_low','avg_precipitation'])

  month  avg_high  avg_low  record_high  record_low  avg_precipitation
0   Jan        58       42           74          22               2.95
1   Feb        61       45           78          26               3.02
2   Mar        65       48           84          25               2.34
3   Apr        67       50           92          28               1.02

In [ ]:
data = [['Jan',58,42,74,22,2.95],
  ['Feb',61,45,78,26,3.02],
  ['Mar',65,48,84,25,2.34],
  ['Apr',67,50,92,28,1.02]]
df = pd.DataFrame(data, index = [0,1,2,3],
                  columns = ['month','avg_high','avg_low','record_high','record_low','avg_precipitation'])

In [24]:
# Create a data frame with your class information (courseID, courseName, creditHours, Days) and save it as an Excel file. 이번학기에 듣는 클래스의 정보를 이용하여 데이터프레임을 만드시오.
courses = {
    'couseID': [1111, 2222, 3333],
    'courseName': ['DM', 'web crawling', 'algorithm'],
    'creditHours': [3, 3, 3],
    'Days': ['Mon', 'Tues', 'Thur']
}
df = pd.DataFrame(courses)
df

   couseID    courseName  creditHours  Days
0     1111            DM            3   Mon
1     2222  web crawling            3  Tues
2     3333     algorithm            3  Thur